### ISSUE TITLE
在fedora23 64位 不能编译

### ISSUE THREAD

**Issue by 728443778** [xueguoliang/xs#1]
你好 薛老师，我从网上了解到xs库，就clone了下来学习，但发现在我的系统上不能编译，这是编译信息输出的文件
- 
  [compile.txt](https://github.com/xueguoliang/xs/files/362794/compile.txt)

**Comment by 728443778** [comment]
不好意思 是我搞错了， 我没发现那个可执行文件，结果是要把目录放到src下才行

**Comment by xueguoliang** [comment]
OK
